### ISSUE TITLE
Print list of detected object

### ISSUE THREAD

**Issue by alisurajaya** [vindruid/yolov3-in-colab#1]
I have successful use yolov3 pytorch on google colab to detecting object from a video file. But I need to get the list of detected object. How to get list of detected object like this?
image 2/2 data/samples/zidane.jpg: 256x416 2 persons, 1 ties, Done. (0.085s)

**Comment by vindruid** [comment]
Hi @alisurajaya , you can extract (or print) the label of object from these lines, inside function `predict_one_video` 

```python
                for *xyxy, conf, cls in det:
                    label = '%s %.2f' % (names[int(cls)], conf)
                    plot_one_box(xyxy, im0, label=label, color=colors[int(cls)])
```

print the `label` variable, or store it in a list so you can get result like 2 persons, 1 tie,

**Comment by alisurajaya** [comment]
thank you, but what label variable should i write to get the list of detected object? Can you give me the example?

**Comment by vindruid** [comment]
@alisurajaya , you should write the `label` variable 

for example if you want to print list of detected per object 
put your new variable `list_detected_object` inside the while loop 
```python
    while img0 is not None: 
    list_detected_object = []  # <<- THIS IS NEW LINE
     ........

                # Write results
                for *xyxy, conf, cls in det:
                    label = '%s %.2f' % (names[int(cls)], conf)
                    list_detected_object.append(label)  # <<- THIS IS NEW LINE
                    plot_one_box(xyxy, im0, label=label, color=colors[int(cls)])

        vid_writer.write(im0)
        print(list_detected_object) # <<- THIS IS NEW LINE
        _, img0 = cap.read()
```

**Comment by alisurajaya** [comment]
![Screen Shot 2020-06-01 at 19 52 16](https://user-images.githubusercontent.com/47766351/83410934-7cb09c00-a441-11ea-912d-e79f0ce805f8.png)

but why the output like this? should I write something inside list_detected_object =[] ?

**Comment by alisurajaya** [comment]
Thank you very much, I've already get the list of detected object. But is there any way to separate the list based on the object ID?

**Comment by vindruid** [comment]
could you elaborate on the `list` that you mean? 
or could you share the context / what kind of project you are working on, it might be easier to help :D

**Comment by alisurajaya** [comment]
Ya, I'm trying to create project for vehicle counting. Can I use that code for that purpose?

**Comment by vindruid** [comment]
@alisurajaya you can but you need to add an object tracker in order to get object ID. 

The codes in [here](https://colab.research.google.com/github/vindruid/yolov3-in-colab/blob/master/yolov3_video.ipynb) is actually predicting object in a frame, it does not associate object between frames, which you need in-vehicle counting. 

You can find some tracker here: 
[centroid tracker](https://www.pyimagesearch.com/2018/07/23/simple-object-tracking-with-opencv/)
[SORT](https://github.com/abewley/sort) 

Combine the YOLO model + Object Tracker + a few rows of codes = could solve your problem :D

**Comment by alisurajaya** [comment]
I will explore more about tracker, thanks a lot for your help. May I still contact you for consulting about my project?

**Comment by vindruid** [comment]
@alisurajaya sure, glad to help

**Comment by alisurajaya** [comment]
Dear kak @vindruid, could you guide me how to modify this [people counter](https://www.pyimagesearch.com/2018/08/13/opencv-people-counter/) code for vehicle counting purpose that can count car, motorbike, bus, and bicycle? Because I'm beginner and trying to modify the code by myself but not yet successful. Hope you can help me, thanks

**Comment by vindruid** [comment]
Hi Kak @alisurajaya 
The key is on `cls` variabel, produced here 

```python
                # Write results
                for *xyxy, conf, cls in det:
                    label = '%s %.2f' % (names[int(cls)], conf)
                    plot_one_box(xyxy, im0, label=label, color=colors[int(cls)])
```

this is an example to plot only **car** and **motorbike**
```python
                # Write results
                for *xyxy, conf, cls in det:
                    if cls in [2,3]:
                         label = '%s %.2f' % (names[int(cls)], conf)
                         plot_one_box(xyxy, im0, label=label, color=colors[int(cls)])
                         # append to some list here, if you have a list to produce
```
It only processes `cls` index of  2 or 3, the magical numbers are from [here](https://github.com/ultralytics/yolov3/blob/master/data/coco.names).
As python convention, we start from `0` for `person` then `2` for `car` and `3` for `motorcycle`

**Comment by alisurajaya** [comment]
So where should I add/insert the object tracker code?
